server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
    registry-fetch-interval-seconds: 5
    eureka-service-url-poll-interval-seconds: 5

spring:
  application:
    name: TaskManager-gateway-service
  cloud:
    gateway:
      routes:
        - id: TaskManager-task-service
          uri: lb://TaskManager-task-service
          predicates:
            - Path=/v1/api/task/**
        - id: TaskManager-user-service
          uri: lb://TaskManager-user-service
          predicates:
            - Path=/v1/api/user/**

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    disable-swagger-default-url: true
    enabled: true
    path: /
    urls:
      - url: /v1/api/user/api-docs
        name: TaskManager-user-service-docs
        primaryName: TaskManager-user-service-docs
      - url: /v1/api/task/api-docs
        name: TaskManager-task-service-docs
        primaryName: TaskManager-task-service-docs
